version: "3.8"
services:
  bot:
    build: .
    env_file: ./.env.local
    restart: unless-stopped
  postgres:
    ports:
      - "127.0.0.1:5432:5432"
    image: postgres:15.4-alpine
    restart: "no"
    env_file: ./.env.local
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: